version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clientsdb
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    #initialize the database with model_database/load_tables.py
    #command: sh -c "python3 load_tables.py"
  
  # load:
  #   image: python:3.8
  #   restart: always
  #   volumes:
  #     - ./load_tables.py:/load_tables.py
  #     - .raw_data:/raw_data
  #     - ./requirements.txt:/requirements.txt
  #   command: pip install -r requirements.txt
  #     #- sh -c "python3 load_tables.py"

volumes:
  db:
    driver: local